version: "3"

services:
  frontend:
    build: ./frontend
    stdin_open: true
    volumes:
      - ./frontend/src:/src
      - ./frontend/node_modules:/node_modules
    ports:
      - "3000:3000"
