version: '3'

services:
  application:
    image: ''
    stdin_open: true
    ports:
      - ':'
    depends_on:
      - userdata
    environment:
      - GH_CLIENT_ID=
      - GH_CLIENT_SECRET=
      - GH_CB_URL=
      - JWT_SECRET=
      - PORT=
      - DATABASE_URL=

  userdata:
    image: 'postgres'
    env_file:
      - ./userdata/userdata.env
    volumes:
      - ./userdata/init_scripts/:/docker-entrypoint-initdb.d/
      - userdata-data:/var/lib/postgresql/data/
    ports:
      - ':'

  watchtower:
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

volumes:
  userdata-data:
