version: '2.1'

services:
  testbackend:
    command: sh -c "yarn run migrate-up-prod && yarn test"
    build: ./backend
    stdin_open: true
    volumes:
      - ./backend/:/usr/src/app
      - ./backend/node_modules:/usr/src/app/node_modules
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=postgres://test:test@testdata:5431/test
    depends_on:
      testdata:
        condition: service_healthy

  testdata:
    image: 'postgres'
    command: -p 5431
    environment:
      - POSTGRES_USER=test
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=test
    ports:
      - '5431:5431'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test -p 5431 -d test']
      interval: 5s
      timeout: 5s
      retries: 5
