version: "3"

services:
  frontend:
    command: whoami
    build: ./frontend
    stdin_open: true
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
