name: WEVC CI/CD

on:
  push:
    branches: [master, ci-configuration]
    paths-ignore:
      - 'documentation/**'
      - 'README.md'
      - LICENSE

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install frontend
        run: cd frontend && yarn
      - name: Test frontend
        run: cd frontend && yarn test --watchAll=false --passWithNoTests
      - name: Build frontend
        run: cd frontend && yarn build
      - name: Install backend
        run: cd backend && yarn
      - name: Test backend
        run: echo 'no tests yet'
      - name: Build backend
        run: cd backend && yarn build
      - name: Start backend for Cypress tests
        run: cd backend && nohup node build/src/index.js &
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./frontend
          start: yarn start
          wait-on: http://localhost:3000

  CD:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker build frontend
        run: cd frontend && docker build -t front .
      - name: Docker tag frontend
        run: docker tag front ${{ secrets.DOCKER_REPO }}:frontend-latest
      - name: Docker push frontend
        run: docker push ${{ secrets.DOCKER_REPO }}:frontend-latest
      - name: Docker build backend
        run: cd backend && docker build -t back .
      - name: Docker tag backend
        run: docker tag back ${{ secrets.DOCKER_REPO }}:backend-latest
      - name: Docker push backend
        run: docker push ${{ secrets.DOCKER_REPO }}:backend-latest
