name: STAGING PULL REQUEST

on:
  pull_request:
    branches: [staging]
    paths-ignore:
      - 'documentation/**'
      - 'README.md'
      - LICENSE

jobs:
  TEST:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Setup actions
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install, build and test frontend
        run: |
          cd frontend
          yarn
          yarn build
          yarn test --watchAll=false

      - name: Install, build, test and start token service # start necessary for backend tests
        run: |
          cd tokenservice
          yarn
          yarn tsc
          yarn test
          NODE_ENV=e2etest yarn start &

      - name: Install, build and test backend
        run: |
          cd backend
          yarn
          yarn build
          yarn migrate-up-citest
          yarn test-ci
        env:
          DATABASE_URL_TEST: postgres://test:test@localhost:${{ job.services.postgres.ports[5432] }}/test
          DATABASE_URL: postgres://test:test@localhost:${{ job.services.postgres.ports[5432] }}/test
          TOKEN_SERVICE_URL: http://localhost:3002

      - name: Start server for E2E tests
        run: |
          cp -r frontend/build backend/build/frontBuild
          cd backend
          yarn migrate-up-prod
          NODE_ENV=e2etest node ./build/index.js &
        env:
          NODE_ENV: e2etest
          DATABASE_URL_TEST: postgres://test:test@localhost:${{ job.services.postgres.ports[5432] }}/test
          DATABASE_URL: postgres://test:test@localhost:${{ job.services.postgres.ports[5432] }}/test
          GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
          GL_CLIENT_ID: ${{ secrets.GL_CLIENT_ID }}
          GL_CLIENT_SECRET: ${{ secrets.GL_CLIENT_SECRET }}
          BB_CLIENT_ID: ${{ secrets.BB_CLIENT_ID }}
          BB_CLIENT_SECRET: ${{ secrets.BB_CLIENT_SECRET }}
          TOKEN_SERVICE_URL: http://localhost:3002

      - name: E2E testing
        uses: cypress-io/github-action@v2
        with:
          working-directory: frontend
          wait-on: http://localhost:3001
          env: configFile=production

      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-snapshots
          path: frontend/cypress/screenshots
