name: STAGING PULL REQUEST

on:
  pull_request:
    branches: [staging]
    paths-ignore:
      - 'documentation/**'
      - 'README.md'
      - LICENSE
jobs:
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [14.x]
  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install frontend
      run: cd frontend && yarn

    - name: Test frontend
      run: cd frontend && yarn test --watchAll=false --passWithNoTests

    - name: Build frontend
      run: cd frontend && yarn build

    - name: Install backend
      run: cd backend && yarn

    - name: Test backend
      run: echo 'no tests yet'

    - name: Build backend
      run: cd backend && yarn build

    - name: Start backend for Cypress tests
      run: cd backend && yarn run start &
      env:
        GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
        GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}

    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        working-directory: ./frontend
        start: yarn start
        wait-on: http://localhost:3000
