name: STAGING PULL REQUEST

on:
  pull_request:
    branches: [staging]
    paths-ignore:
      - 'documentation/**'
      - 'README.md'
      - LICENSE
jobs:
  TEST:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Setup actions
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install, build and test frontend
        run: |
          cd frontend
          yarn
          yarn build
          yarn test --watchAll=false --passWithNoTests

      - name: Install, build and test backend
        run: |
          cd backend
          yarn
          yarn build 
          yarn test

      - name: Start server for E2E tests
        run: |
          cd backend 
          yarn run start &
        env:
          GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
          GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}

      - name: E2E testing
        uses: cypress-io/github-action@v2
        with:
          working-directory: frontend
          start: yarn start
          wait-on: http://localhost:3000
